
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--explicit-package-bases, --ignore-missing-imports]
        always_run: false
        stages: [manual]
  - repo: local
    hooks:
      - id: data-validation
        name: dataloader validation
        entry: uv run pre_commit_check.py
        language: script
        pass_filenames: false
        language: system
        always_run: true
